import React from 'react';

export default function PrivacyPolicySection() {
  return (
    <section id="privacy-policy" className="py-20 px-4 bg-gradient-to-b from-gray-50 to-white">
      <div className="max-w-4xl mx-auto">
        {/* Header */}
        <div className="text-center mb-12">
          <h1 className="text-4xl md:text-5xl font-bold text-gray-900 mb-4">
            Privacy Policy
          </h1>
          <p className="text-gray-600">Last updated: December 15, 2025</p>
        </div>

        {/* Content */}
        <div className="bg-white rounded-2xl shadow-lg p-8 md:p-12 space-y-8">
          {/* Introduction */}
          <div>
            <p className="text-gray-700 leading-relaxed">
              This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
            </p>
            <p className="text-gray-700 leading-relaxed mt-4">
              We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.
            </p>
          </div>

          {/* Interpretation and Definitions */}
          <div>
            <h2 className="text-2xl font-bold text-gray-900 mb-4">Interpretation and Definitions</h2>
            
            <h3 className="text-xl font-semibold text-gray-800 mb-3 mt-6">Interpretation</h3>
            <p className="text-gray-700 leading-relaxed">
              The words whose initial letters are capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
            </p>

            <h3 className="text-xl font-semibold text-gray-800 mb-3 mt-6">Definitions</h3>
            <p className="text-gray-700 mb-3">For the purposes of this Privacy Policy:</p>
            <div className="space-y-3 pl-4 border-l-4 border-blue-500">
              <p className="text-gray-700"><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</p>
              <p className="text-gray-700"><strong>Affiliate</strong> means an entity that controls, is controlled by, or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</p>
              <p className="text-gray-700"><strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to Climmatech, IIT MANDI North Campus Himachal Pradesh India.</p>
              <p className="text-gray-700"><strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</p>
              <p className="text-gray-700"><strong>Country</strong> refers to: Himachal Pradesh, India</p>
              <p className="text-gray-700"><strong>Device</strong> means any device that can access the Service such as a computer, a cell phone or a digital tablet.</p>
              <p className="text-gray-700"><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</p>
              <p className="text-gray-700"><strong>Service</strong> refers to the Website.</p>
              <p className="text-gray-700"><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company.</p>
              <p className="text-gray-700"><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself.</p>
              <p className="text-gray-700"><strong>Website</strong> refers to Climmatech, accessible from <a href="https://www.climmatech.com/" className="text-blue-600 hover:underline">https://www.climmatech.com/</a></p>
              <p className="text-gray-700"><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</p>
            </div>
          </div>

          {/* Collecting and Using Your Personal Data */}
          <div>
            <h2 className="text-2xl font-bold text-gray-900 mb-4">Collecting and Using Your Personal Data</h2>
            
            <h3 className="text-xl font-semibold text-gray-800 mb-3 mt-6">Types of Data Collected</h3>
            
            <h4 className="text-lg font-semibold text-gray-800 mb-2 mt-4">Personal Data</h4>
            <p className="text-gray-700 mb-2">While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:</p>
            <ul className="list-disc list-inside text-gray-700 space-y-1 ml-4">
              <li>Email address</li>
              <li>First name and last name</li>
              <li>Usage Data</li>
            </ul>

            <h4 className="text-lg font-semibold text-gray-800 mb-2 mt-4">Usage Data</h4>
            <p className="text-gray-700 mb-2">Usage Data is collected automatically when using the Service.</p>
            <p className="text-gray-700 mb-2">Usage Data may include information such as Your Device's Internet Protocol address, browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</p>
            <p className="text-gray-700">When You access the Service by or through a mobile device, We may collect certain information automatically, including the type of mobile device You use, Your mobile device's unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.</p>
          </div>

          {/* Tracking Technologies and Cookies */}
          <div>
            <h3 className="text-xl font-semibold text-gray-800 mb-3">Tracking Technologies and Cookies</h3>
            <p className="text-gray-700 mb-3">We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. The technologies We use may include:</p>
            <div className="bg-gray-50 rounded-lg p-6 space-y-4">
              <div>
                <p className="font-semibold text-gray-800">Necessary / Essential Cookies</p>
                <p className="text-gray-700 text-sm">Type: Session Cookies</p>
                <p className="text-gray-700 text-sm">Purpose: These Cookies are essential to provide You with services available through the Website and to enable You to use some of its features.</p>
              </div>
              <div>
                <p className="font-semibold text-gray-800">Cookies Policy / Notice Acceptance Cookies</p>
                <p className="text-gray-700 text-sm">Type: Persistent Cookies</p>
                <p className="text-gray-700 text-sm">Purpose: These Cookies identify if users have accepted the use of cookies on the Website.</p>
              </div>
              <div>
                <p className="font-semibold text-gray-800">Functionality Cookies</p>
                <p className="text-gray-700 text-sm">Type: Persistent Cookies</p>
                <p className="text-gray-700 text-sm">Purpose: These Cookies allow us to remember choices You make when You use the Website.</p>
              </div>
            </div>
          </div>

          {/* Use of Your Personal Data */}
          <div>
            <h3 className="text-xl font-semibold text-gray-800 mb-3">Use of Your Personal Data</h3>
            <p className="text-gray-700 mb-3">The Company may use Personal Data for the following purposes:</p>
            <ul className="list-disc list-inside text-gray-700 space-y-2 ml-4">
              <li>To provide and maintain our Service, including to monitor the usage of our Service</li>
              <li>To manage Your Account as a user of the Service</li>
              <li>For the performance of a contract for products, items or services You have purchased</li>
              <li>To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication</li>
              <li>To provide You with news, special offers, and general information about other goods and services</li>
              <li>To manage Your requests to Us</li>
              <li>For business transfers in case of merger, divestiture, restructuring, or sale of assets</li>
              <li>For other purposes such as data analysis and improving our Service</li>
            </ul>
          </div>

          {/* Sharing Personal Information */}
          <div>
            <h3 className="text-xl font-semibold text-gray-800 mb-3">Sharing Your Personal Information</h3>
            <p className="text-gray-700 mb-2">We may share Your personal information in the following situations:</p>
            <ul className="list-disc list-inside text-gray-700 space-y-2 ml-4">
              <li><strong>With Service Providers:</strong> To monitor and analyze the use of our Service</li>
              <li><strong>For business transfers:</strong> In connection with any merger, sale of Company assets, or acquisition</li>
              <li><strong>With Affiliates:</strong> We may share Your information with Our affiliates</li>
              <li><strong>With business partners:</strong> To offer You certain products, services or promotions</li>
              <li><strong>With Your consent:</strong> For any other purpose with Your consent</li>
            </ul>
          </div>

          {/* Data Retention */}
          <div>
            <h3 className="text-xl font-semibold text-gray-800 mb-3">Retention of Your Personal Data</h3>
            <p className="text-gray-700">The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations, resolve disputes, and enforce our legal agreements and policies.</p>
          </div>

          {/* Delete Your Personal Data */}
          <div>
            <h3 className="text-xl font-semibold text-gray-800 mb-3">Delete Your Personal Data</h3>
            <p className="text-gray-700 mb-2">You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You.</p>
            <p className="text-gray-700">You may update, amend, or delete Your information at any time by signing in to Your Account and visiting the account settings section. You may also contact Us to request access to, correct, or delete any personal information that You have provided to Us.</p>
          </div>

          {/* Security */}
          <div>
            <h3 className="text-xl font-semibold text-gray-800 mb-3">Security of Your Personal Data</h3>
            <p className="text-gray-700">The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially reasonable means to protect Your Personal Data, We cannot guarantee its absolute security.</p>
          </div>

          {/* Children's Privacy */}
          <div>
            <h3 className="text-xl font-semibold text-gray-800 mb-3">Children's Privacy</h3>
            <p className="text-gray-700">Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us.</p>
          </div>

          {/* Links to Other Websites */}
          <div>
            <h3 className="text-xl font-semibold text-gray-800 mb-3">Links to Other Websites</h3>
            <p className="text-gray-700">Our Service may contain links to other websites that are not operated by Us. We strongly advise You to review the Privacy Policy of every site You visit. We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.</p>
          </div>

          {/* Changes to Privacy Policy */}
          <div>
            <h3 className="text-xl font-semibold text-gray-800 mb-3">Changes to this Privacy Policy</h3>
            <p className="text-gray-700 mb-2">We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.</p>
            <p className="text-gray-700">You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.</p>
          </div>

          {/* Contact Us */}
          <div className="bg-blue-50 rounded-lg p-6 mt-8">
            <h3 className="text-xl font-semibold text-gray-800 mb-3">Contact Us</h3>
            <p className="text-gray-700 mb-2">If you have any questions about this Privacy Policy, You can contact us:</p>
            <p className="text-gray-700">
              By visiting this page on our website: <a href="https://www.climmatech.com/#contact" className="text-blue-600 hover:underline font-medium">https://www.climmatech.com/#contact</a>
            </p>
          </div>
        </div>
      </div>
    </section>
  );
}